#!/bin/bash

# retrieve notebooks and place correctly in session
rm index.ipynb
git clone https://github.com/sawula/datasci_mods_content.git
cp datasci_mods_content/index.ipynb .
mv datasci_mods_content/notebooks .
rm -rf datasci_mods_content

# this must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
