channels:
  - conda-forge
dependencies:
  - python=3.8
  - altair
  - cairo
  - cairosvg
  - jedi=0.17.2
  - jupyterlab
  - line_profiler
  - matplotlib
  - noise
  - pandas
  - pip
  - vega_datasets
  - pip:
    - py5
